# Source: cluster-api-aws/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cp5lc0bn2-capi-aws
  namespace: cp5lc0bn2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cp5lc0bn2-capi-aws
subjects:
- kind: ServiceAccount
  name: cp5lc0bn2-capi-aws
